# Generated by Django 5.2.11 on 2026-02-27 16:07

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '__first__'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='upload/product_images/%Y/%m/')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this product publicly visible.', verbose_name='Actif')),
                ('product_code', models.CharField(blank=True, editable=False, help_text='Product code of added item.', max_length=255, null=True, unique=True, verbose_name='Product code')),
                ('ean13', models.CharField(blank=True, max_length=13, verbose_name='EAN13')),
                ('uom', models.CharField(choices=[('BG', 'Bag'), ('BR', 'Barrel'), ('BL', 'Block'), ('B8', 'Board'), ('BF', 'Board Feet'), ('BO', 'Bottle'), ('BX', 'Box'), ('BN', 'Bulk'), ('BD', 'Bundle'), ('CG', 'Card'), ('CT', 'Carton'), ('CQ', 'Cartridge'), ('CA', 'Case'), ('C3', 'Centigram'), ('CM', 'Centiliter'), ('1N', 'Count'), ('CC', 'Cubic Centimeter'), ('C8', 'Cubic Decimeter'), ('CF', 'Cubic Feet'), ('CI', 'Cubic Inches'), ('CR', 'Cubic Meter'), ('MMQ', 'Cubic Milimetre'), ('DA', 'Days'), ('DG', 'Decigram'), ('DL', 'Deciliter'), ('DM', 'Decimeter'), ('CE', 'Degrees Celsius'), ('FA', 'Degrees Fahrenheit'), ('DZ', 'Dozen'), ('FT', 'Feet'), ('UZ', 'Fifty Count'), ('UY', 'Fifty Square Feet'), ('FO', 'Fluid Ounce'), ('GA', 'Gallon'), ('GR', 'Gram'), ('GT', 'Gross Kilogram'), ('HD', 'Half Dozen'), ('HC', 'Houndred Count'), ('HL', 'Houndred Feet'), ('CW', 'Houndred Pounds'), ('IN', 'Inches'), ('JR', 'Jar'), ('KG', 'Kilogram'), ('DK', 'Kilometer'), ('KT', 'Kit'), ('LT', 'Liter'), ('MR', 'Meter'), ('MP', 'Metric Ton'), ('MC', 'Microgram'), ('4G', 'Microliter'), ('ME', 'Miligram'), ('ML', 'Mililiter'), ('MM', 'Milimeter'), ('OZ', 'Ounces'), ('PH', 'Pack'), ('PK', 'Package'), ('PA', 'Pail'), ('PR', 'Pair'), ('PL', 'Pallet'), ('P1', 'Percent'), ('PC', 'Piece'), ('PT', 'Pint'), ('PTN', 'Portion'), ('V2', 'Pouch'), ('ST', 'Set'), ('SH', 'Sheet'), ('SF', 'Square Foot'), ('SM', 'Square Meter'), ('SY', 'Square Yard'), ('TK', 'Tank'), ('TM', 'Thousand Feet'), ('UN', 'Unit'), ('YD', 'Yard')], default='UN', max_length=20, verbose_name='UOM')),
                ('uos', models.CharField(choices=[('BG', 'Bag'), ('BR', 'Barrel'), ('BL', 'Block'), ('B8', 'Board'), ('BF', 'Board Feet'), ('BO', 'Bottle'), ('BX', 'Box'), ('BN', 'Bulk'), ('BD', 'Bundle'), ('CG', 'Card'), ('CT', 'Carton'), ('CQ', 'Cartridge'), ('CA', 'Case'), ('C3', 'Centigram'), ('CM', 'Centiliter'), ('1N', 'Count'), ('CC', 'Cubic Centimeter'), ('C8', 'Cubic Decimeter'), ('CF', 'Cubic Feet'), ('CI', 'Cubic Inches'), ('CR', 'Cubic Meter'), ('MMQ', 'Cubic Milimetre'), ('DA', 'Days'), ('DG', 'Decigram'), ('DL', 'Deciliter'), ('DM', 'Decimeter'), ('CE', 'Degrees Celsius'), ('FA', 'Degrees Fahrenheit'), ('DZ', 'Dozen'), ('FT', 'Feet'), ('UZ', 'Fifty Count'), ('UY', 'Fifty Square Feet'), ('FO', 'Fluid Ounce'), ('GA', 'Gallon'), ('GR', 'Gram'), ('GT', 'Gross Kilogram'), ('HD', 'Half Dozen'), ('HC', 'Houndred Count'), ('HL', 'Houndred Feet'), ('CW', 'Houndred Pounds'), ('IN', 'Inches'), ('JR', 'Jar'), ('KG', 'Kilogram'), ('DK', 'Kilometer'), ('KT', 'Kit'), ('LT', 'Liter'), ('MR', 'Meter'), ('MP', 'Metric Ton'), ('MC', 'Microgram'), ('4G', 'Microliter'), ('ME', 'Miligram'), ('ML', 'Mililiter'), ('MM', 'Milimeter'), ('OZ', 'Ounces'), ('PH', 'Pack'), ('PK', 'Package'), ('PA', 'Pail'), ('PR', 'Pair'), ('PL', 'Pallet'), ('P1', 'Percent'), ('PC', 'Piece'), ('PT', 'Pint'), ('PTN', 'Portion'), ('V2', 'Pouch'), ('ST', 'Set'), ('SH', 'Sheet'), ('SF', 'Square Foot'), ('SM', 'Square Meter'), ('SY', 'Square Yard'), ('TK', 'Tank'), ('TM', 'Thousand Feet'), ('UN', 'Unit'), ('YD', 'Yard')], default='UN', max_length=20, verbose_name='UOS')),
                ('uom_to_uos', models.FloatField(default=1.0, help_text='Conversion rate between UOM and UOS', verbose_name='UOM to UOS')),
                ('weight', models.FloatField(default=1.0, verbose_name='unit weight (Kg)')),
                ('is_consumable', models.BooleanField(default=False, verbose_name='consumable?')),
                ('is_service', models.BooleanField(default=False, verbose_name='service?')),
                ('sales_price', models.FloatField(default=0.0, verbose_name='sales price')),
                ('sales_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar')], default='EUR', max_length=3, verbose_name='sales currency')),
                ('max_sales_discount', models.FloatField(default=0.0, verbose_name='max sales discount (%)')),
                ('sales_tax', models.FloatField(default=0.0, verbose_name='sales tax (%)')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('RSV', 'Reserved'), ('SLD', 'Sold'), ('PND', 'Pending'), ('UNV', 'Unavailable'), ('CMS', 'Coming Soon'), ('UCN', 'Under Construction'), ('MNT', 'Under Maintenance'), ('DSC', 'Discontinued'), ('RNT', 'Rented')], default='AVL', max_length=3)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taxonomy.mpcategory')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload/product_images/%Y/%m/')),
                ('thumbnail_path', models.CharField(max_length=50, null=True, verbose_name='thumbnail')),
                ('large_path', models.CharField(max_length=50, null=True, verbose_name='large')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productspecification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.producttype', verbose_name='Specification'),
        ),
    ]
