# Generated by Django 5.2.11 on 2026-02-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productspecificationvalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecificationvalue',
            options={},
        ),
    ]
