# Generated by Django 5.2.11 on 2026-02-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Cocher pour définir cette image comme image principale du produit', verbose_name='Image principale'),
        ),
    ]
