# Generated by Django 4.2.11 on 2026-02-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productspecificationvalue_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productspecificationvalue",
            options={"base_manager_name": "objects"},
        ),
    ]
