# Generated by Django 5.2.11 on 2026-02-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmagic_sport', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0002_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sportproduct',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_cmagic_sport_slug'),
        ),
    ]
