# Generated by Django 5.2.11 on 2026-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmagic_sport', '0002_sportproduct_unique_cmagic_sport_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sportproduct',
            name='unique_cmagic_sport_slug',
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='brand',
            field=models.CharField(blank=True, choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Jordan', 'Jordan'), ('Puma', 'Puma'), ('Under Armour', 'Under Armour'), ('New Balance', 'New Balance'), ('Reebok', 'Reebok'), ('Converse', 'Converse'), ('Vans', 'Vans'), ('Asics', 'Asics'), ('Other', 'Other')], max_length=50, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='color_secondary',
            field=models.CharField(blank=True, max_length=50, verbose_name='Couleur secondaire'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='colorway',
            field=models.CharField(blank=True, max_length=100, verbose_name='Coloris'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Homme'), ('Women', 'Femme'), ('Kids', 'Enfant'), ('Unisex', 'Unisexe')], max_length=20, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='material',
            field=models.CharField(blank=True, choices=[('Leather', 'Cuir'), ('Synthetic', 'Synthétique'), ('Mesh', 'Mesh'), ('Canvas', 'Toile'), ('Suede', 'Suède'), ('Knit', 'Tricot'), ('Other', 'Autre')], max_length=50, verbose_name='Matériau'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du modèle'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='size_eu',
            field=models.CharField(blank=True, max_length=10, verbose_name='Taille EU'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='size_uk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Taille UK'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='size_us',
            field=models.CharField(blank=True, max_length=10, verbose_name='Taille US'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='style_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code style'),
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='technologies',
            field=models.TextField(blank=True, verbose_name='Technologies'),
        ),
    ]
