# Generated by Django 5.2.11 on 2026-02-28 19:11

import cmagic_sport.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmagic_sport', '0003_add_brand_fields'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='colorway',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='material',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='size_eu',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='size_uk',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='size_us',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='style_code',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='technologies',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('shipping_address', models.TextField(verbose_name='Adresse de livraison')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Ville')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('shipping_country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default=cmagic_sport.models.OrderStatus.get_default, max_length=20, verbose_name='Statut')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de suivi')),
                ('tracking_url', models.URLField(blank=True, verbose_name='URL de suivi')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Transporteur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition")),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant taxes')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmagic_orders', to='customer.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU du produit')),
                ('product_size', models.CharField(blank=True, max_length=20, verbose_name='Taille')),
                ('product_color', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('product_brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('product_image', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmagic_sport.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='cmagic_sport.sportproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Élément de commande',
                'verbose_name_plural': 'Éléments de commande',
            },
        ),
    ]
