# Generated by Django 5.2.11 on 2026-02-27 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyé', 'Envoyé'), ('en_attente', 'En attente'), ('accepté', 'Accepté'), ('refusé', 'Refusé'), ('expiré', 'Expiré'), ('converti', 'Converti en facture')], default='brouillon', max_length=50, verbose_name='Statut du devis')),
                ('completed', models.BooleanField(default=False)),
                ('quote_terms', models.TextField(blank=True, verbose_name='Quote_terms')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='product.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='devis.quote')),
            ],
            options={
                'verbose_name': 'Élément de devis',
                'verbose_name_plural': 'Éléments de devis',
            },
        ),
    ]
