# Generated by Django 5.2.11 on 2026-02-27 16:07

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiers_id', models.CharField(max_length=3)),
                ('tiers_name', models.CharField(max_length=100)),
                ('tiers_type', models.CharField(choices=[('C', 'Client'), ('F', 'Fornisseur')], default='F', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('visibilite', models.CharField(choices=[('P', 'Projet Public'), ('I', 'Projet interne'), ('C', 'Projet lié à un client'), ('V', 'Projet privé seulement au abonnés')], default='Projet Public', max_length=100, verbose_name='visiblite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(verbose_name="date d'echeance")),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='closed on')),
                ('start_date', models.DateTimeField(verbose_name='date debut')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date fin')),
                ('comment', models.TextField(blank=True, null=True)),
                ('default_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='upload/product_images/%Y/%m/')),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PLANNING', 'En planification'), ('PRE_CONSTRUCTION', 'Pré-construction'), ('UNDER_CONSTRUCTION', 'En construction'), ('COMPLETED', 'Terminé'), ('SELLING', 'En vente'), ('SOLD_OUT', 'Vendu'), ('CANCELLED', 'Annulé'), ('ON_HOLD', 'En attente'), ('RENOVATING', 'En rénovation')], default='PLANNING', max_length=20, verbose_name='Statut du project')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetcs', to='taxonomy.mpcategory')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='project manager')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.societe')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['slug'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload/product_images/%Y/%m/')),
                ('thumbnail_path', models.CharField(max_length=50, null=True, verbose_name='thumbnail')),
                ('large_path', models.CharField(max_length=50, null=True, verbose_name='large')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('optional', 'Optional'), ('low', 'Low'), ('important', 'Important'), ('urgent', 'Urgent')], default='optional', max_length=20, verbose_name='Priority')),
                ('task_type', models.CharField(choices=[('action', 'Action'), ('task', 'Task'), ('idea', 'Idea'), ('milestone', 'Milestone')], default='action', max_length=20, verbose_name='Task Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Priority')),
                ('ticket_type', models.CharField(choices=[('bug', 'Bug'), ('task', 'Task'), ('idea', 'Idea'), ('feature', 'Feature Request'), ('support', 'Support')], default='bug', max_length=20, verbose_name='Ticket Type')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved at')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='project.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
