# Generated by Django 5.2.11 on 2026-02-28 10:49

import django.db.models.deletion
import invoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('devis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyée', 'Envoyée'), ('en_attente', 'En attente'), ('partiellement_payée', 'Partiellement payée'), ('payée', 'Payée'), ('en_retard', 'En retard'), ('annulée', 'Annulée'), ('remboursée', 'Remboursée'), ('contestée', 'Contestée'), ('abandonnée', 'Abandonnée'), ('approuvée', 'Approuvée'), ('en_cours_de_traitement', 'En cours de traitement'), ('échue', 'Échue'), ('crédit', 'Crédit')], default='brouillon', max_length=50, verbose_name='Statut de la facture')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(default=invoice.models.get_default_expiration_date)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_terms', models.TextField(blank=True, default='NET 30 Days. Finance Charge of 1.5% will be         made on unpaid balances after 30 days.')),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('devis_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis.quote', verbose_name='Devis source')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
            ],
        ),
    ]
